[package]
name = "tokio"

# When releasing to crates.io:
# - Update html_root_url.
# - Update CHANGELOG.md.
# - Update doc URL.
# - Create "v0.1.x" git tag.
version = "0.1.12"
authors = ["Carl Lerche <me@carllerche.com>"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/tokio/0.1.12/tokio/"
repository = "https://github.com/tokio-rs/tokio"
homepage = "https://tokio.rs"
description = """
An event-driven, non-blocking I/O platform for writing asynchronous I/O
backed applications.
"""
categories = ["asynchronous", "network-programming"]
keywords = ["io", "async", "non-blocking", "futures"]

[workspace]

members = [
  "./",
  "tokio-async-await",
  "tokio-buf",
  "tokio-channel",
  "tokio-codec",
  "tokio-current-thread",
  "tokio-executor",
  "tokio-fs",
  "tokio-io",
  "tokio-reactor",
  "tokio-signal",
  "tokio-threadpool",
  "tokio-timer",
  "tokio-tcp",
  "tokio-tls",
  "tokio-udp",
  "tokio-uds",
]

[features]
# This feature comes with no promise of stability. Things will
# break with each patch release. Use at your own risk.
async-await-preview = [
  "tokio-async-await/async-await-preview",
]

[badges]
travis-ci = { repository = "tokio-rs/tokio" }
appveyor = { repository = "carllerche/tokio", id = "s83yxhy9qeb58va7" }

[dependencies]
bytes = "0.4"
num_cpus = "1.8.0"
tokio-codec = "0.1.0"
tokio-current-thread = "0.1.3"
tokio-io = "0.1.6"
tokio-executor = "0.1.5"
tokio-reactor = "0.1.1"
tokio-threadpool = "0.1.4"
tokio-tcp = "0.1.0"
tokio-udp = "0.1.0"
tokio-timer = { path = "tokio-timer" }
tokio-fs = "0.1.3"

futures = "0.1.20"

# Needed until `reactor` is removed from `tokio`.
mio = "0.6.14"

# Needed for async/await preview support
tokio-async-await = { version = "0.1.0", optional = true }

[target.'cfg(unix)'.dependencies]
tokio-uds = "0.2.1"

[dev-dependencies]
env_logger = { version = "0.5", default-features = false }
flate2 = { version = "1", features = ["tokio"] }
futures-cpupool = "0.1"
http = "0.1"
httparse = "1.0"
libc = "0.2"
num_cpus = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1"
